config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 275557 # Put your project id here

profile: jaffle_shop # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  jaffle_shop:
    +schema: raw
    jaffle-data:
      +enabled: "{{ var('load_source_data', true) }}"

models:
  jaffle_shop:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

data_tests:
  +store_failures: true
  +schema: dqs

vars:
  "dbt_date:time_zone": "America/Los_Angeles"
  openmetadata_jwt_token: 'eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZyIsInN1YiI6ImFkbWluIiwicm9sZXMiOlsiQWRtaW4iXSwiZW1haWwiOiJhZG1pbkBvcGVuLW1ldGFkYXRhLm9yZyIsImlzQm90IjpmYWxzZSwidG9rZW5UeXBlIjoiT01fVVNFUiIsInVzZXJuYW1lIjoiYWRtaW4iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTc3NDM3MDY4OCwiZXhwIjoxNzc0Mzc0Mjg4fQ.Q99CyTInWYXQwZL7_3kUeJ6ycsXwWkknJFGu2W2Jq-U2tBsrY1cyi3dqgYrkGdeM_EZCfCAFt0gHCHZ9fS3EO3_mzzHk-I1Ie1su5wQ8w_nd4fUHeck_61t26rr7SOFLO5EDI7uFVM_WGqXs1O7rqHMPPjpqUDlqBNaWu_xwkNrNv8wSxkaeEOnXsb6FAN--vtRqu2ZUdJfDIIvhO3rXp5msi-ZpgYFe7w8d_o44qKqAlFk17A21IWW0Gn7dxaLa30tXYNsKh2K8jIZfBTB9GId45aNmRW_2cabEAJl2_Izo0Xag22aGeXitGGA4wgdN0uUpFHYe-IpU19dLlrTO3w'
  openmetadata_host_port: 'http://localhost:8585/api'
  openmetadata_service_name: 'local_postgres_dbt'