config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 275557 # Put your project id here

profile: jaffle_shop # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  jaffle_shop:
    +schema: raw
    jaffle-data:
      +enabled: "{{ var('load_source_data', true) }}"

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table

vars:
  "dbt_date:time_zone": "America/Los_Angeles"
  openmetadata_jwt_token: 'eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZyIsInN1YiI6ImFkbWluIiwicm9sZXMiOlsiQWRtaW4iXSwiZW1haWwiOiJhZG1pbkBvcGVuLW1ldGFkYXRhLm9yZyIsImlzQm90IjpmYWxzZSwidG9rZW5UeXBlIjoiT01fVVNFUiIsInVzZXJuYW1lIjoiYWRtaW4iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiIsImlhdCI6MTc3MzkzOTQ2OCwiZXhwIjoxNzczOTQzMDY4fQ.nMsUgliQhTCu3soZJRfX4H1p7mSesIer7VmqLOEw67PPTDfT0H9OTyudPWehawCVtlzrrIgMoeaIBhkSedp7DEHG97KtW-ri3jUog-nB5O_2Z2vfI9JIk_zSyssJKGLXabtPiafQiXertBdISzboKUHX5iG9tkp9USewSAo_--Bl0XJZ92o174iWTgJ2FaY0ClwSqt8hPDcn1wTgaROBIF7_Zqyd_w-qtwMYVOeH2aQdGbctI1gfKQvfgRZmAhc_dG2prcM_oI09AeqZuKfBlFKkU_vCtX_hrbB71y7GdO9WeDNbk5rdnaxV5TX43T6qX6mH1ZNZhIH2jWKPAlR44Q'
  openmetadata_host_port: 'http://localhost:8585/api'
  openmetadata_service_name: 'local_postgres_dbt'