[project]
name = "dbt-openmetadata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-duckdb>=1.10.1",
    "jafgen>=0.4.14",
    "openmetadata-ingestion[dbt,duckdb]>=1.12.1.0",
    "pre-commit>=4.5.1",
    "requests>=2.32.5",
    "sqlfluff>=4.0.4",
]
