[project]
name = "dbt-openmetadata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.12.0",
    "cachetools>=7.0.5",
    "dbt-artifacts-parser>=0.13.0",
    "dbt-postgres>=1.10.0",
    "dlt[duckdb]>=1.24.0",
    "jafgen>=0.4.14",
    "openmetadata-ingestion[dbt,duckdb]>=1.12.1.0",
    "pre-commit>=4.5.1",
    "requests>=2.32.5",
    "rich>=14.3.3",
    "sqlfluff>=4.0.4",
]
